on:
  push:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\psf-prerequisites.ps1 -Bootstrap
      shell: powershell
    - name: Build Docs
      run: .\build\build-docs.ps1
      shell: powershell
    - name: Validate
      run: .\build\validate.ps1
      shell: powershell
    - name: Build
      run: .\build\publish.ps1 -ApiKey $env:APIKEY -UsePSF
      shell: powershell
      env:
        APIKEY: ${{ secrets.ApiKey }}
