on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\prerequisites.ps1
      shell: powershell
    - name: Build Docs
      run: .\build\build-docs.ps1
      shell: powershell
    - name: Validate
      run: .\build\validate.ps1
      shell: powershell
    - name: Build
      run: .\build\publish.ps1 -ApiKey $env:APIKEY
      shell: powershell
      env:
        APIKEY: ${{ secrets.ApiKey }}
